# Generated by Django 5.2 on 2025-05-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_useraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrow_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Prix de l'emprunt du livre", max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text="Prix d'achat du livre", max_digits=10),
        ),
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'exemplaires disponibles"),
        ),
    ]
