# Generated by Django 5.2 on 2025-05-25 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_borrow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='borrow',
            options={'ordering': ['-borrow_date']},
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='borrowed_at',
            new_name='borrow_date',
        ),
        migrations.RenameField(
            model_name='borrow',
            old_name='returned_at',
            new_name='return_date',
        ),
        migrations.AddField(
            model_name='borrow',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
