# Generated by Django 5.2 on 2025-05-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_borrow_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('fiction', 'Fiction'), ('non_fiction', 'Non-fiction'), ('science', 'Science'), ('histoire', 'Histoire'), ('biographie', 'Biographie'), ('informatique', 'Informatique'), ('art', 'Art'), ('cuisine', 'Cuisine'), ('jeunesse', 'Jeunesse'), ('autre', 'Autre')], default='fiction', max_length=50),
        ),
        migrations.DeleteModel(
            name='Borrow',
        ),
    ]
